
ARG FROM_STR="droidmate"

FROM ${FROM_STR}


ARG API_ARG="24"
ENV API=${API_ARG}
ARG ARCH_ARG="x86_64"
ENV ARCH=${ARCH_ARG}
ARG TOOL_COMMIT_ARG="dev"
ENV TOOL_COMMIT=${TOOL_COMMIT_ARG}


#
# Emulator
# 

# Install
RUN echo yes | ${ANDROID_SDK_FOLDER}/tools/bin/sdkmanager "system-images;android-${API};google_apis;${ARCH}"

# AVD
ENV AVD_NAME="droidmate_nexus5_${API}_gapps_${ARCH}"
RUN avdmanager create avd -n "${AVD_NAME}" -k "system-images;android-${API};google_apis;${ARCH}" -d "Nexus 5"


#
# DroiMate
#

# Build
RUN cd ${TOOL_PATH} && \
    git checkout ${TOOL_COMMIT} && \
    sync && \
    ./gradlew build && \
    ./gradlew shadowJar


#
# Entrypoint
#

COPY ./entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh
# ENTRYPOINT [ "bash", "/root/entrypoint.sh" ]